ALTER TABLE "User"
    ALTER COLUMN  "createdAt" TYPE TIMESTAMPTZ,
    ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ;

ALTER TABLE "Profile"
    ALTER COLUMN  "createdAt" TYPE TIMESTAMPTZ,
    ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ;

ALTER TABLE "Farm"
    ALTER COLUMN  "createdAt" TYPE TIMESTAMPTZ,
    ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ;
